name: Deploy on GCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy: 
    name: Setup GCP Account
    runs-on: ubuntu-latest
    environment: prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
        
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      
      - name: Push Docker Image
        run: docker push $IMAGE_NAME
        
      - name: Deploy Image
        run: gcloud run deploy site --image $IMAGE_NAME --region us-central1 --memory 128Mi --min-instance 1 --plataform managed --port 80 --allow-unauthenticated
  
